import { DesignNumbers } from "@/components/design-numbers";
import { hasAnyRole, hasRole, canWorkStage } from "@/lib/roles";
import { OrderAssignment } from "@/components/order-assignment";
import { ManagerNotes } from "@/components/manager-notes";
import { InteractivePipeline } from "@/components/interactive-pipeline";
import { QcInspection } from "@/components/qc-inspection";
import { currentUser } from "@/lib/current-user";
import { prisma } from "@/lib/prisma";
import { notFound, redirect } from "next/navigation";
import { activeStitchingReworkTailorIds } from "@/lib/qc-rework";

const sizes = [38, 40, 42, 44, 46, 48, 50];

export default async function OrderDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const actor = await currentUser();
  if (!actor) redirect("/login");
  const canAssign = hasAnyRole(actor, ["ADMIN", "ORDER_MANAGER"]);
  const { id } = await params;
  const [order, staff] = await Promise.all([
    prisma.order.findUnique({ where: { id }, include: { customer: true, createdBy: { select: { id: true, name: true, phone: true, role: true, roles: true } }, items: { include: { sizeQuantities: true } }, rawMaterials: true, batches: true, qcInspection: true, assignments: { include: { user: { select: { id: true, name: true, role: true, roles: true, phone: true } } } }, statusUpdates: { include: { user: { select: { id: true, name: true } } }, orderBy: { createdAt: "desc" }, take: 100 }, managerNotes: { include: { author: { select: { name: true } } }, orderBy: { createdAt: "desc" }, take: 50 }, laborCosts: { where: canAssign ? {} : { userId: actor.id }, include: { user: { select: { id: true, name: true } } }, orderBy: { createdAt: "desc" }, take: 100 } } }),
    prisma.user.findMany({ where: { isActive: true }, select: { id: true, name: true, role: true, roles: true }, orderBy: { name: "asc" } }),
  ]);
  if (!order) notFound();
  const total = order.items.flatMap((item) => item.sizeQuantities).reduce((sum, line) => sum + line.quantity, 0);
  const reworkTailorIds = activeStitchingReworkTailorIds(order.currentStage, order.qcInspection);
  const isAssignedCurrentWorker = order.assignments.some((assignment) => assignment.stage === order.currentStage && canWorkStage(actor, order.currentStage, assignment.userId)) && (!reworkTailorIds.length || reworkTailorIds.includes(actor.id));
  const canUpdateStatus = order.currentStage === "STITCHING" ? isAssignedCurrentWorker : canAssign || isAssignedCurrentWorker;
  const isAssignedQcWorker = hasRole(actor, "QC_INSPECTOR") && order.currentStage === "QUALITY_CHECK" && order.assignments.some((assignment) => assignment.stage === "QUALITY_CHECK" && assignment.userId === actor.id);
  const visibleManagerNotes = canAssign ? order.managerNotes : order.managerNotes.filter((note) => order.assignments.some((assignment) => assignment.userId === actor.id && assignment.stage === note.stage));
  const stitchingWorkers = order.assignments.filter(assignment => assignment.stage === "STITCHING" && (!reworkTailorIds.length || reworkTailorIds.includes(assignment.userId))).map(assignment => assignment.user);
  const activeWorkers = order.assignments.filter(assignment => assignment.stage === order.currentStage).map(assignment => assignment.user);
  const fallbackManager = !order.createdBy && order.productionManager ? await prisma.user.findFirst({ where: { name: order.productionManager, role: { in: ["ADMIN", "ORDER_MANAGER"] }, isActive: true }, select: { id: true, name: true, phone: true, role: true, roles: true } }) : null;
  const orderManager = order.createdBy || fallbackManager;
  const whatsappContacts = canAssign ? (stitchingWorkers.length ? stitchingWorkers : activeWorkers) : orderManager ? [orderManager] : [];
  const whatsappTargets = whatsappContacts.map(contact => { const number = contact.phone?.replace(/\D/g, ""); return { contact, href: number ? `https://wa.me/${number}?text=${encodeURIComponent(`Hello ${contact.name}, regarding job order ${order.orderNumber} (${order.garmentName}) — ${order.currentStage.replaceAll("_", " ")}.`)}` : null }; });

  return <main className="detail-shell">
    <header className="detail-header"><div><a className="back-link" href="/orders">← All job orders</a><DesignNumbers items={order.items} prominent /><p className="eyebrow">Job order {order.orderNumber}</p><h1>{order.garmentName}</h1><p className="muted">{order.customer.name} · {order.processName || "Process not set"}</p></div><div className="detail-actions">{canAssign ? <><a className="text-button" href={`/orders/${order.id}/billing`}>Tailor billing</a><a className="text-button" href={`/orders/${order.id}/edit`}>Edit order</a></> : null}<a className="primary" href={`/orders/${order.id}/label`}>{canAssign ? "Print QR label" : "View QR"}</a><div className="detail-total"><span>Total garments</span><b>{total}</b></div></div></header>
    <InteractivePipeline actorId={actor.id} orderId={order.id} orderNumber={order.orderNumber} designs={order.items.flatMap(item => item.designCode?.trim() ? [{ code: item.designCode.trim(), name: item.itemName }] : [])} currentStage={order.currentStage} status={order.status} eta={order.estimatedCompletion?.toISOString() || null} assignments={order.assignments} updates={order.statusUpdates.map((update) => ({ ...update, eta: update.eta?.toISOString() || null, createdAt: update.createdAt.toISOString() }))} costs={order.laborCosts.map((cost) => ({ ...cost, amount: cost.amount.toString(), createdAt: cost.createdAt.toISOString() }))} canUpdate={canUpdateStatus} canManage={canAssign} managerContact={orderManager ? { name: orderManager.name, phone: orderManager.phone } : null} qcInspection={order.qcInspection ? { result: order.qcInspection.result, stitchingPassed: order.qcInspection.stitchingPassed, measurementPassed: order.qcInspection.measurementPassed, finishingPassed: order.qcInspection.finishingPassed, rejectionReason: order.qcInspection.rejectionReason, reworkStage: order.qcInspection.reworkStage, reworkTailorIds: order.qcInspection.reworkTailorIds, reworkDesignCodes: order.qcInspection.reworkDesignCodes, updatedAt: order.qcInspection.updatedAt.toISOString(), defectPhotoPath: order.qcInspection.defectPhotoPath } : null} canInspectQc={isAssignedQcWorker} />
    {order.currentStage === "STITCHING" && order.qcInspection?.result === "REWORK_REQUIRED" && (canAssign || reworkTailorIds.includes(actor.id)) ? <QcInspection orderId={order.id} inspection={{ result: order.qcInspection.result, stitchingPassed: order.qcInspection.stitchingPassed, measurementPassed: order.qcInspection.measurementPassed, finishingPassed: order.qcInspection.finishingPassed, rejectionReason: order.qcInspection.rejectionReason, reworkStage: order.qcInspection.reworkStage, reworkTailorIds: order.qcInspection.reworkTailorIds, reworkDesignCodes: order.qcInspection.reworkDesignCodes, updatedAt: order.qcInspection.updatedAt.toISOString(), defectPhotoPath: order.qcInspection.defectPhotoPath }} canInspect={false} designs={order.items.flatMap(item => item.designCode?.trim() ? [{ code: item.designCode.trim(), name: item.itemName }] : [])} tailors={order.assignments.filter(item => item.stage === "STITCHING").map(item => ({ id: item.user.id, name: item.user.name }))} /> : null}
    <section className="detail-grid"><article><p className="eyebrow">Client</p><h2>{order.customer.name}</h2><p>{order.customer.phone || "No contact number"}</p><p>{order.customer.address || "No address recorded"}</p></article><article><p className="eyebrow">Document details</p><dl><div><dt>Issue no.</dt><dd>{order.issueNumber || "—"}</dd></div><div><dt>Sales order</dt><dd>{order.salesOrderNumber || "—"}</dd></div><div><dt>Manager</dt><dd>{order.productionManager || "—"}</dd></div>{canAssign ? <div><dt>Inward value</dt><dd>{order.inwardValue ? `₹${order.inwardValue.toString()}` : "—"}</dd></div> : null}<div><dt>Received</dt><dd>{order.receivedDate?.toLocaleDateString("en-IN") || "—"}</dd></div></dl></article></section>
    {canAssign ? <OrderAssignment orderId={order.id} staff={staff} assignments={order.assignments} canAssign={canAssign} /> : null}
    <ManagerNotes orderId={order.id} currentStage={order.currentStage} notes={visibleManagerNotes.map((note) => ({ ...note, createdAt: note.createdAt.toISOString() }))} canManage={canAssign} />
    <section className="detail-section"><div className="section-heading"><div><p className="eyebrow">Finish</p><h2>Finished garment breakdown</h2></div><span className={`order-status ${order.status.toLowerCase()}`}>{order.status.replace("_", " ")}</span></div>{order.items.map((item) => { const values = new Map(item.sizeQuantities.map((line) => [line.size, line.quantity])); return <div className="size-breakdown" key={item.id}><div className="item-caption"><DesignNumbers items={[item]} /><b>{item.itemName}</b><span>Color {item.color || "—"}</span></div>{sizes.map((size) => <div key={size}><small>Size {size}</small><b>{values.get(size) || 0}</b></div>)}</div>; })}</section>
    <section className="detail-section"><div className="section-heading"><div><p className="eyebrow">Raw</p><h2>Raw-material inward</h2></div><div className="raw-material-summary"><span>{order.rawMaterials.length} items</span><b>Total ₹{order.rawMaterials.reduce((sum, material) => sum + Number(material.cost), 0).toFixed(2)}</b></div></div>{order.rawMaterials.length ? <div className="material-detail-table"><div><span>Item code</span><span>Item name</span><span>Color</span><span>Panna</span><span>Quantity</span><span>Material cost</span></div>{order.rawMaterials.map((material) => <div key={material.id}><b>{material.itemCode || "—"}</b><b>{material.itemName}</b><span>{material.color || "—"}</span><span>{material.panna?.toString() || "—"}</span><span>{material.quantity.toString()} {material.unit}</span><strong>₹{Number(material.cost).toFixed(2)}</strong></div>)}</div> : <p className="muted">No raw-material inward entries recorded.</p>}</section>
    {whatsappTargets.length === 1 && whatsappTargets[0].href ? <a className="whatsapp-float" href={whatsappTargets[0].href!} target="_blank" rel="noreferrer" aria-label={`Message ${whatsappTargets[0].contact.name} on WhatsApp`}><b>◔</b><span>{canAssign ? `Message ${whatsappTargets[0].contact.name}` : "Message order manager"}</span></a> : whatsappTargets.length > 1 ? <details className="whatsapp-float whatsapp-multi"><summary><b>◔</b><span>WhatsApp {whatsappTargets.length} tailors</span></summary><div>{whatsappTargets.map(({ contact, href }) => href ? <a href={href} target="_blank" rel="noreferrer" key={contact.id}>Message {contact.name}</a> : <span key={contact.id}>{contact.name}<small>No phone number</small></span>)}</div></details> : null}
  </main>;
}
