ALTER TABLE `Order`
  MODIFY `currentStage` ENUM('CUTTING','FUSING','STITCHING','QUALITY_CHECK','PACKING','DELIVERY') NOT NULL DEFAULT 'CUTTING',
  MODIFY `status` ENUM('CREATED','IN_PROGRESS','ON_HOLD','COMPLETED','NOT_REQUIRED','CANCELLED') NOT NULL DEFAULT 'CREATED';

ALTER TABLE `OrderAssignment` MODIFY `stage` ENUM('CUTTING','FUSING','STITCHING','QUALITY_CHECK','PACKING','DELIVERY') NOT NULL;
ALTER TABLE `OrderStatusUpdate`
  MODIFY `stage` ENUM('CUTTING','FUSING','STITCHING','QUALITY_CHECK','PACKING','DELIVERY') NOT NULL,
  MODIFY `status` ENUM('CREATED','IN_PROGRESS','ON_HOLD','COMPLETED','NOT_REQUIRED','CANCELLED') NOT NULL;
ALTER TABLE `OrderManagerNote` MODIFY `stage` ENUM('CUTTING','FUSING','STITCHING','QUALITY_CHECK','PACKING','DELIVERY') NOT NULL;
ALTER TABLE `LaborCostEntry` MODIFY `stage` ENUM('CUTTING','FUSING','STITCHING','QUALITY_CHECK','PACKING','DELIVERY') NOT NULL;
ALTER TABLE `QcInspection` MODIFY `reworkStage` ENUM('CUTTING','FUSING','STITCHING','QUALITY_CHECK','PACKING','DELIVERY') NULL;
ALTER TABLE `ProductionBatch`
  MODIFY `currentStage` ENUM('CUTTING','FUSING','STITCHING','QUALITY_CHECK','PACKING','DELIVERY') NOT NULL DEFAULT 'CUTTING',
  MODIFY `status` ENUM('CREATED','IN_PROGRESS','ON_HOLD','COMPLETED','NOT_REQUIRED','CANCELLED') NOT NULL DEFAULT 'CREATED';
ALTER TABLE `ProductionEvent` MODIFY `stage` ENUM('CUTTING','FUSING','STITCHING','QUALITY_CHECK','PACKING','DELIVERY') NOT NULL;

INSERT INTO `OrderStatusUpdate` (`id`,`orderId`,`status`,`stage`,`comment`,`eta`,`userId`,`createdAt`)
SELECT UUID(), o.`id`, 'NOT_REQUIRED', 'FUSING', 'Existing order — fusing marked not required', NULL,
  COALESCE(o.`createdById`, (SELECT u.`id` FROM `User` u WHERE u.`role` IN ('ADMIN','ORDER_MANAGER') ORDER BY u.`createdAt` ASC LIMIT 1)), NOW()
FROM `Order` o
WHERE NOT EXISTS (SELECT 1 FROM `OrderStatusUpdate` osu WHERE osu.`orderId` = o.`id` AND osu.`stage` = 'FUSING')
  AND COALESCE(o.`createdById`, (SELECT u.`id` FROM `User` u WHERE u.`role` IN ('ADMIN','ORDER_MANAGER') LIMIT 1)) IS NOT NULL;
