"use client";
export type DesignItem = { itemName: string; designCode: string; color: string; clientOrderReference: string; sizeQuantities: { size: number; quantity: number }[] };
const sizes = [38,40,42,44,46,48,50];
export const blankDesignItem = (): DesignItem => ({ itemName: "", designCode: "", color: "", clientOrderReference: "", sizeQuantities: sizes.map(size => ({size, quantity:0})) });
export function DesignItemsEditor({items,onChange}:{items:DesignItem[];onChange:(items:DesignItem[])=>void}) {
 const total = items.flatMap(item => item.sizeQuantities).reduce((sum,item)=>sum+item.quantity,0);
 const update = (index:number,changes:Partial<DesignItem>) => onChange(items.map((item,i)=>i===index?{...item,...changes}:item));
 return <section><div className="section-heading"><div><p className="eyebrow">Design identification</p><h2>Designs & garment quantities</h2></div><b className="quantity-total">Total: {total}</b></div><p className="muted">Design number is required for each design and appears first when scanning.</p>{items.map((item,index)=><fieldset className="design-edit-item" key={index}><legend>Design {index+1}</legend><div className="form-grid"><label>Design number<input required maxLength={191} value={item.designCode} placeholder="e.g. D-1042" onChange={e=>update(index,{designCode:e.target.value})} /></label><label>Item name<input required value={item.itemName} onChange={e=>update(index,{itemName:e.target.value})} /></label><label>Color<input value={item.color} onChange={e=>update(index,{color:e.target.value})} /></label><label>Client order ref.<input value={item.clientOrderReference} onChange={e=>update(index,{clientOrderReference:e.target.value})} /></label></div><div className="size-grid">{sizes.map(size=><label key={size}>Size {size}<input type="number" min="0" step="1" value={item.sizeQuantities.find(entry=>entry.size===size)?.quantity || ""} onChange={e=>update(index,{sizeQuantities:sizes.map(value=>({size:value,quantity:value===size?Number(e.target.value):item.sizeQuantities.find(entry=>entry.size===value)?.quantity||0}))})} /></label>)}</div>{items.length>1&&<button type="button" className="text-button" onClick={()=>onChange(items.filter((_,i)=>i!==index))}>Remove design {index+1}</button>}</fieldset>)}<button type="button" className="text-button" onClick={()=>onChange([...items,blankDesignItem()])}>+ Add another design</button></section>;
}
