"use client";

import { DesignItemsEditor, blankDesignItem, DesignItem } from "@/components/design-items-editor";
import { useState } from "react";

const sizes = [38, 40, 42, 44, 46, 48, 50];
type FormOrder = { id: string; customer: { name: string; phone: string | null; address: string | null }; orderNumber: string; issueNumber: string | null; processName: string | null; salesOrderNumber: string | null; productionManager: string | null; receivedDate: string | null; inwardValue: string | null; garmentName: string; items: { designCode: string | null; itemName: string; color: string | null; clientOrderReference: string | null; sizeQuantities: { size: number; quantity: number }[] }[]; rawMaterials: { itemCode: string | null; itemName: string; color: string | null; panna: string | null; quantity: string; unit: string; cost: string }[] };

export function EditOrderForm({ order }: { order: FormOrder }) {
  const item = order.items[0];
  const [designItems, setDesignItems] = useState<DesignItem[]>(order.items.length ? order.items.map(item => ({ ...item, designCode: item.designCode || "", color: item.color || "", clientOrderReference: item.clientOrderReference || "" })) : [blankDesignItem()]);
  const [materials, setMaterials] = useState(order.rawMaterials.length ? order.rawMaterials.map((material) => ({ ...material, itemCode: material.itemCode || "", color: material.color || "", panna: material.panna || "" })) : [{ itemCode: "", itemName: "", color: "", panna: "", quantity: "", unit: "m", cost: "" }]);
  const [message, setMessage] = useState("");
  async function submit(data: FormData) { setMessage(""); const payload = { customer: { name: data.get("customerName"), phone: data.get("phone"), address: data.get("address") }, orderNumber: data.get("orderNumber"), issueNumber: data.get("issueNumber"), processName: data.get("processName"), salesOrderNumber: data.get("salesOrderNumber"), productionManager: data.get("productionManager"), receivedDate: data.get("receivedDate"), inwardValue: data.get("inwardValue") ? Number(data.get("inwardValue")) : undefined, garmentName: designItems[0].itemName, items: designItems, rawMaterials: materials.filter((line) => line.itemName.trim()).map((line) => ({ ...line, panna: line.panna ? Number(line.panna) : undefined, quantity: Number(line.quantity) || 0, cost: Number(line.cost) || 0 })) }; const response = await fetch(`/api/orders/${order.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const body = await response.json(); if (response.ok) window.location.assign(`/orders/${order.id}`); else setMessage(body.error || "Unable to update order."); }
  return <form action={submit} className="intake-form"><section><div className="form-heading"><div><p className="eyebrow">Edit client document</p><h1>Edit job order</h1></div><a href={`/orders/${order.id}`} className="text-button">← Cancel</a></div><div className="form-grid"><label>Client name<input name="customerName" required defaultValue={order.customer.name} /></label><label>Contact number<input name="phone" defaultValue={order.customer.phone || ""} /></label><label className="wide">Address<textarea name="address" rows={2} defaultValue={order.customer.address || ""} /></label></div></section><section><h2>Job order details</h2><div className="form-grid"><label>Job order no.<input name="orderNumber" required defaultValue={order.orderNumber} /></label><label>Issue no.<input name="issueNumber" defaultValue={order.issueNumber || ""} /></label><label>Process name<input name="processName" required defaultValue={order.processName || ""} /></label><label>Sales order no.<input name="salesOrderNumber" defaultValue={order.salesOrderNumber || ""} /></label><label>Production manager<input name="productionManager" defaultValue={order.productionManager || ""} /></label><label>Date received<input name="receivedDate" type="date" defaultValue={order.receivedDate?.slice(0, 10) || ""} /></label><label>Inward value<input name="inwardValue" type="number" min="0" step="0.01" defaultValue={order.inwardValue || ""} /></label></div></section><DesignItemsEditor items={designItems} onChange={setDesignItems} /><section><div className="section-heading"><div><p className="eyebrow">Raw</p><h2>Raw-material inward</h2></div><button type="button" className="text-button" onClick={() => setMaterials([...materials, { itemCode: "", itemName: "", color: "", panna: "", quantity: "", unit: "m", cost: "" }])}>+ Add material</button></div><div className="materials">{materials.map((line, index) => <div className="material-row" key={index}>{(["itemCode", "itemName", "color", "panna", "quantity", "unit", "cost"] as const).map((field) => <input key={field} aria-label={field} placeholder={field === "itemCode" ? "Item code" : field === "itemName" ? "Item name" : field === "panna" ? "Panna" : field === "quantity" ? "Quantity" : field === "unit" ? "Unit" : field === "cost" ? "Material cost ₹" : "Color"} type={field === "panna" || field === "quantity" || field === "cost" ? "number" : "text"} step="0.01" value={line[field]} onChange={(event) => { const next = [...materials]; next[index][field] = event.target.value; setMaterials(next); }} />)}</div>)}</div></section><div className="form-actions"><p aria-live="polite">{message}</p><button className="primary" type="submit">Save changes</button></div></form>;
}
