"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";

type Update = { id: string; status: string; stage: string; comment: string | null; eta: string | null; createdAt: string; user: { name: string } };
const stageLabel = (stage?: string) => (stage || "CUTTING").replaceAll("_", " ");
export function OrderStatusUpdate({ orderId, currentStatus, currentStage, eta, updates, canUpdate, completionLabel }: { orderId: string; currentStatus: string; currentStage: string; eta: string | null; updates: Update[]; canUpdate: boolean; completionLabel?: string }) {
  const router = useRouter(); const [status, setStatus] = useState(currentStatus === "CREATED" ? "IN_PROGRESS" : currentStatus); const [comment, setComment] = useState(""); const [estimatedCompletion, setEstimatedCompletion] = useState(eta?.slice(0, 16) || ""); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  async function submit() { setSaving(true); setMessage(""); const response = await fetch(`/api/orders/${orderId}/status`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status, comment, eta: estimatedCompletion }) }); const body = await response.json(); if (response.ok) { setComment(""); setMessage("Status updated."); router.refresh(); } else setMessage(body.error || "Unable to update status."); setSaving(false); }
  return <section className="detail-section status-update"><div className="section-heading"><div><p className="eyebrow">Current work status</p><h2>{stageLabel(currentStage)} stage</h2></div><span className={`order-status ${currentStatus.toLowerCase()}`}>{currentStatus.replace("_", " ")}</span></div>{canUpdate ? <div className="status-form"><label>Status<select value={status} onChange={(event) => setStatus(event.target.value)}><option value="IN_PROGRESS">In progress</option><option value="ON_HOLD">On hold</option><option value="COMPLETED">{completionLabel || "Completed — send to next stage"}</option>{currentStage === "FUSING" ? <option value="NOT_REQUIRED">Not required — continue to Stitching</option> : <option value="CANCELLED">Cancelled</option>}</select></label><label>Estimated completion<input type="datetime-local" value={estimatedCompletion} onChange={(event) => setEstimatedCompletion(event.target.value)} /></label><label className="status-comment">Comments<textarea value={comment} onChange={(event) => setComment(event.target.value)} placeholder="Add progress notes. Required for on hold or cancelled." rows={2} /></label><div className="status-form-action"><p aria-live="polite">{message}</p><button className="primary" disabled={saving} onClick={submit}>{saving ? "Saving…" : "Update status"}</button></div></div> : <p className="muted">Only the worker assigned to the current stage, Admin, or Order Manager can update this order.</p>}<div className="status-history"><h3>Update history</h3>{updates.length ? updates.map((update) => <article key={update.id}><div><b>{stageLabel(update.stage)} · {update.status.replace("_", " ")}</b><span>{update.user.name} · {new Date(update.createdAt).toLocaleString("en-IN")}</span></div>{update.eta ? <small>ETA: {new Date(update.eta).toLocaleString("en-IN")}</small> : null}{update.comment ? <p>{update.comment}</p> : null}</article>) : <p className="muted">No status updates yet.</p>}</div></section>;
}
