ALTER TABLE `Order`
  ADD COLUMN `currentStage` ENUM('CUTTING', 'STITCHING', 'QUALITY_CHECK', 'PACKING', 'DELIVERY') NOT NULL DEFAULT 'CUTTING';

ALTER TABLE `OrderStatusUpdate`
  ADD COLUMN `stage` ENUM('CUTTING', 'STITCHING', 'QUALITY_CHECK', 'PACKING', 'DELIVERY') NOT NULL DEFAULT 'CUTTING';
