import { currentUser } from "@/lib/current-user";
import { prisma } from "@/lib/prisma";
import { redirect } from "next/navigation";

const workerRoles = ["CUTTING_OPERATOR", "TAILOR", "QC_INSPECTOR", "PACKING_STAFF", "DELIVERY_COORDINATOR"] as const;
const roleLabels: Record<string, string> = { CUTTING_OPERATOR: "Cutting", TAILOR: "Tailor", QC_INSPECTOR: "QC", PACKING_STAFF: "Packing", DELIVERY_COORDINATOR: "Delivery" };

export default async function ProductivityPage() {
  const actor = await currentUser(); if (!actor) redirect("/login"); if (!["ADMIN", "ORDER_MANAGER"].includes(actor.role)) redirect("/");
  const [workers, orders, costs] = await Promise.all([
    prisma.user.findMany({ where: { isActive: true, role: { in: [...workerRoles] } }, select: { id: true, name: true, role: true }, orderBy: { name: "asc" } }),
    prisma.order.findMany({ include: { items: { include: { sizeQuantities: true } }, assignments: true, statusUpdates: { orderBy: { createdAt: "asc" } } } }),
    prisma.laborCostEntry.findMany({ select: { userId: true, amount: true, isAccepted: true } }),
  ]);
  const rows = workers.map((worker) => { const active = orders.filter((order) => order.status !== "COMPLETED" && order.status !== "CANCELLED" && order.currentStage && order.assignments.some((assignment) => assignment.userId === worker.id && assignment.stage === order.currentStage)); const completions = orders.flatMap((order) => order.statusUpdates.filter((update) => update.userId === worker.id && update.status === "COMPLETED").map((update) => ({ order, update }))); const completedPieces = completions.reduce((sum, item) => sum + item.order.items.flatMap((line) => line.sizeQuantities).reduce((qty, line) => qty + line.quantity, 0), 0); const durations = completions.map(({ order, update }) => { const start = order.statusUpdates.find((candidate) => candidate.stage === update.stage && candidate.status === "IN_PROGRESS" && candidate.createdAt <= update.createdAt); return start ? update.createdAt.getTime() - start.createdAt.getTime() : null; }).filter((value): value is number => value !== null); const workerCosts = costs.filter((cost) => cost.userId === worker.id); return { ...worker, active: active.length, completedPieces, averageHours: durations.length ? durations.reduce((a, b) => a + b, 0) / durations.length / 3600000 : null, submitted: workerCosts.reduce((sum, cost) => sum + Number(cost.amount), 0), approved: workerCosts.filter((cost) => cost.isAccepted).reduce((sum, cost) => sum + Number(cost.amount), 0) }; });
  const totalActive = rows.reduce((sum, row) => sum + row.active, 0); const totalPieces = rows.reduce((sum, row) => sum + row.completedPieces, 0); const totalApproved = rows.reduce((sum, row) => sum + row.approved, 0);
  return <main className="productivity-shell"><header className="productivity-header"><div><a className="back-link" href="/">← Dashboard</a><p className="eyebrow">Operations analytics</p><h1>Worker productivity</h1><p className="muted">Live output, workload, turnaround time, and finalized earnings.</p></div><a className="primary" href="/orders">View orders</a></header><section className="productivity-summary"><article><span>Active jobs</span><b>{totalActive}</b></article><article><span>Completed pieces</span><b>{totalPieces}</b></article><article><span>Accepted earnings</span><b>₹{totalApproved.toFixed(2)}</b></article></section><section className="productivity-table"><div className="productivity-title"><div><p className="eyebrow">Current team</p><h2>Individual performance</h2></div><span>Average turnaround uses In progress → Completed stage updates</span></div><div className="productivity-head"><span>Worker</span><span>Pending jobs</span><span>Completed pieces</span><span>Avg. stage time</span><span>Proposed cost</span><span>Accepted earnings</span></div>{rows.map((row) => <article key={row.id}><div><b>{row.name}</b><small>{roleLabels[row.role]}</small></div><b>{row.active}</b><b>{row.completedPieces}</b><b>{row.averageHours === null ? "—" : `${row.averageHours.toFixed(1)} hr`}</b><b>₹{row.submitted.toFixed(2)}</b><b className="approved-earnings">₹{row.approved.toFixed(2)}</b></article>)}</section></main>;
}
