ALTER TABLE `User`
  MODIFY `role` ENUM(
    'ADMIN',
    'ORDER_MANAGER',
    'CUTTING_OPERATOR',
    'FUSING_OPERATOR',
    'TAILOR',
    'QC_INSPECTOR',
    'PACKING_STAFF',
    'DELIVERY_COORDINATOR'
  ) NOT NULL;
